# Generated by Django 4.0.3 on 2022-03-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='ProgramName',
            field=models.CharField(default='program name', max_length=30),
        ),
        migrations.AlterField(
            model_name='program',
            name='domain',
            field=models.CharField(default='domain name', max_length=30),
        ),
    ]
