# Generated by Django 4.0.3 on 2022-03-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_program_programname_alter_program_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Githubdorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DorkName', models.CharField(default='Dork Name', max_length=30)),
            ],
        ),
    ]
