# Generated by Django 4.0.3 on 2022-04-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_googledorks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledorks',
            name='dork_category',
        ),
        migrations.AddField(
            model_name='googledorks',
            name='dork_desc',
            field=models.CharField(default='Dork description', max_length=40),
        ),
    ]
