# Generated by Django 4.0.3 on 2022-04-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_googledorks_dork_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='subdomains',
        ),
        migrations.AddField(
            model_name='program',
            name='domains',
            field=models.TextField(default='Domains Related'),
        ),
        migrations.AlterField(
            model_name='program',
            name='acquisitions',
            field=models.TextField(default='Companies Accuired.'),
        ),
    ]
