# Generated by Django 4.0.3 on 2022-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_methodology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodology',
            name='methodology_content',
            field=models.TextField(default='No Methodology Yet !'),
        ),
    ]
