# Generated by Django 4.0.3 on 2022-04-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_methodology_methodology_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='Program Name', max_length=20)),
                ('in_scope', models.TextField(default='in scope')),
                ('out_scope', models.TextField(default='out scope')),
            ],
        ),
    ]
